### ISSUE TITLE
Error running `yarn hardhat get-address`

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/FEVM-Hardhat-Kit#1]
Got the following error after running `yarn hardhat get-address`:

```shell
yarn hardhat get-address

> yarn run v1.22.19
> $ /Users/johnny/FEVM-Hardhat-Kit/node_modules/.bin/hardhat get-address
> You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.
> 
> We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
> nonce: undefined
> Send faucet funds to this address (f1): f1oc2bpna6gq5zthvsuzt3dcprq5pdwosu7ml2o5i
> An unexpected error occurred:
> 
> TypeError: Cannot read properties of undefined (reading 'slice')
>     at SimpleTaskDefinition.action (/Users/johnny/FEVM-Hardhat-Kit/tasks/get-address.js:48:35)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Environment._runTaskDefinition (/Users/johnny/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
>     at Environment.run (/Users/johnny/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
>     at main (/Users/johnny/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/cli/cli.ts:272:7)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Something to do with _slice_? Not sure if that's a package I need to install, or if it's an internal dependency that's borked.

**Comment by rk-rishikesh** [comment]
Have a look at get-address.js file. Line number 46 mentions that this behaviour is expected if the address has not received Filecoin yet. 

Once you deposit Filecoin on f1 address and try to rerun the command : yarn hardhat get-address, you should be all fine.

**Comment by johnnymatthews** [comment]
> mentions that this behaviour is expected if the address has not received Filecoin yet.

Ah, does that mean that the README isn't up to date then? It says to grab an address from Metamask, add that private key as an env variable, and then run `yarn hardhat get-address`.

Does this project expect a FIL address or an ETH address?

**Comment by rk-rishikesh** [comment]
Yeah. Since the repo is currently under development, the README is for the final version which they will release soon.

You need to provide the private key of Ethereum address. The code is self-sufficient to generate FIL address for you.

**Comment by rk-rishikesh** [comment]
You can refer my [article](https://medium.com/@rvk_rishikesh/deploying-your-first-smart-contract-on-fvm-bc4c33e63cf0) for more details.

**Comment by johnnymatthews** [comment]
Ok nice! I was able to run through things using your tutorial. Thanks!
