### ISSUE TITLE
Error deploying smart contracts to localnet using Docker and Hardhat

### ISSUE THREAD

**Issue by leonardzh** [filecoin-project/fevm-hardhat-kit#121]
I'm attempting to deploy smart contracts to a localnet running within Docker using the command `yarn hardhat deploy` following the [video tutorial](https://www.youtube.com/watch?v=LK9QjOJIPkQ). But I encountered the following error message:
```javascript
An unexpected error occurred:

Error: ERROR processing /Users/zhengliu/easier-all/fevm-hardhat-kit/deploy/00_deploy.js:
ProviderError: failed to estimate gas: CallWithGas failed: call raw get actor: resolution lookup failed (t410f2y5msbadh32itwwe2qhyaohixy5umlp25i3ydpa): resolve address t410f2y5msbadh32itwwe2qhyaohixy5umlp25i3ydpa: actor not found
    at HttpProvider.request (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DeploymentsManager.executeDeployScripts (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DeploymentsManager.runDeploy (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat-deploy/src/index.ts:409:5)
    at Environment._runTaskDefinition (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at Environment.run (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at SimpleTaskDefinition.action (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat-deploy/src/index.ts:555:32)
    at Environment._runTaskDefinition (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at Environment.run (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at SimpleTaskDefinition.action (/Users/zhengliu/easier-all/fevm-hardhat-kit/node_modules/hardhat-deploy/src/index.ts:640:5)
error Command failed with exit code 1.

``` 
The localnet is deployed following [another repo](https://github.com/filecoin-project/filecoin-fvm-localnet).
Any guidance on how to resolve this issue would be greatly appreciated.

**Comment by tafseer-khan** [comment]
I was also having an issue with this, I believe that running `yarn hardhat deploy` will either deploy to the default network or all networks listed in your hardhat.config.js file. Default is set to hyperspace testnet. 

If you have followed the steps in the tutorial, having a local network running, and Fil added to your wallet, you will be able to run `yarn hardhat --network localnet deploy` with no issue, assuming that in your hardhat.cfonig.js defines your local network as "localnet"

**Comment by leonardzh** [comment]
> I was also having an issue with this, running `yarn hardhat deploy` will deploy to the default network. Cloned repository has default set to hyperspace testnet.
> 
> If you have followed the steps in the tutorial, having a local network running, and Fil added to your wallet, you will be able to run `yarn hardhat --network localnet deploy` with no issue, assuming that in your hardhat.config.js defines your local network as "localnet"
> 
> Or you can simply change the Default network in hardhat.config.js . This is probably preferred as otherwise you will need to the network flag for the rest of the commands you you may want to run.

Thank you Tafseer. That solved my issue!
