### ISSUE TITLE
yarn hardhat deploy: Error: cannot find artifact "MinerAPI"

### ISSUE THREAD

**Issue by beatyman** [filecoin-project/FEVM-Hardhat-Kit#18]
```
PS F:\workerspace\go\github.com\FEVM-Hardhat-Kit> yarn hardhat deploy           
yarn run v1.22.17
$ F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\.bin\hardhat deploy
You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.

We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
(node:13644) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Nothing to compile
Wallet Ethereum Address: 0x7FE367a7C6F7137f4c781a1e716Bb3c628Bb4111
Wallet f4Address:  f410fp7rwpj6g64jx6tdydiphc25tyyulwqirqtxkgyq
reusing "SimpleCoin" at 0x50d62c3b9eaf52af4c4ef177af89321b4ca58a4d
An unexpected error occurred:

Error: ERROR processing F:\workerspace\go\github.com\FEVM-Hardhat-Kit\deploy\00_deploy.js:
Error: cannot find artifact "MinerAPI"
    at getArtifact (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\DeploymentsManager.ts:207:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getArtifactFromOptions (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\helpers.ts:508:18)
    at getLinkedArtifact (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\helpers.ts:518:38)
    at _deploy (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\helpers.ts:539:54)
    at _deployOne (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\helpers.ts:934:16)
    at Object.module.exports [as func] (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\deploy\00_deploy.js:62:3)
    at DeploymentsManager.executeDeployScripts (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1220:22)
    at DeploymentsManager.runDeploy (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\index.ts:409:5)
    at DeploymentsManager.executeDeployScripts (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1223:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.runDeploy (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\index.ts:409:5)
    at Environment._runTaskDefinition (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
    at Environment.run (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
    at SimpleTaskDefinition.action (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\index.ts:555:32)
    at Environment._runTaskDefinition (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
    at Environment.run (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
    at SimpleTaskDefinition.action (F:\workerspace\go\github.com\FEVM-Hardhat-Kit\node_modules\hardhat-deploy\src\index.ts:640:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by beatyman** [comment]
```
git submodule update --init --recursive

```
