### ISSUE TITLE
HTTP Error: Provider Error

### ISSUE THREAD

**Issue by AdedamolaXL** [filecoin-project/fevm-hardhat-kit#38]
Hello, am trying to deploy on FEVM for the first time [yarn hardhat deploy] and I get this error, am not sure what it is. Please help, i have inserted the error from the terminal here >
 
 `$ /home/adedamola/DEV/test/FEVM-Hardhat-Kit/node_modules/.bin/hardhat deploy
Nothing to compile
transaction 0x7fb03526953ed8622c07c2f0dfabc022c614b5c8e7e4f01a23c695d9cf68557b still pending... It used a gas pricing config of maxPriorityFeePerGas: 197947 maxFeePerGas: 201262 ,
              current gas price is 198712 wei
              
              
✔ Choose what to do with the pending transaction: · increase gas
legacy transaction is not supported {"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (/home/adedamola/DEV/test/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)\n    at LocalAccountsProvider.request (/home/adedamola/DEV/test/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","code":1,"_isProviderError":true} ProviderError: HttpProviderError
    at HttpProvider.request (/home/adedamola/DEV/test/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/home/adedamola/DEV/test/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
An unexpected error occurred:

ProviderError: HttpProviderError
    at HttpProvider.request (/home/adedamola/DEV/test/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/home/adedamola/DEV/test/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by ZakAyesh** [comment]
Hi, Wallaby was down this past weekend, are you still having this error?

**Comment by AdedamolaXL** [comment]
> Hi, Wallaby was down this past weekend, are you still having this error?

yes i am still getting that error

**Comment by ZakAyesh** [comment]
Hi @AdedamolaXL, the kit has been updated significantly since this issue was created. Following the instructions should now fix this problem. If not please feel free to open another issue.
