### ISSUE TITLE
TyperError when attempting to deploy

### ISSUE THREAD

**Issue by 0xThresh** [filecoin-project/fevm-hardhat-kit#47]
Hello, after running through the initial setup steps described in the README, I attempted to run `yarn hardhat deploy` to get the contracts spun up. However, I ran into the output below and could not deploy the contracts successfully:

```
0xthresh@pc:~/fevm-hardhat-kit$ yarn hardhat deploy --reset
yarn run v1.22.19
$ /home/0xthresh/fevm-hardhat-kit/node_modules/.bin/hardhat deploy --reset
You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.

We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
Nothing to compile
Wallet Ethereum Address: 0xc2b60CfFe4f20b2046C951CDEB459aF897cff571
deploying SimpleCoin...
deploying "SimpleCoin" (tx: 0x144039e1c8ac41de1be224eb93e3b49ee0505718043ff826581f28c0f6ab1682)...
/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1814
                for (let i = 0; i < block.transactions.length; i++) {
                                                       ^
TypeError: Cannot read properties of null (reading 'length')
    at Web3Provider.<anonymous> (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1814:56)
    at step (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

For what it's worth, I know my private key must be set up right, because I get the expected output from `yarn hardhat get-address`: 
```
Ethereum address (this addresss should work for most tools): 0xc2b60CfFe4f20b2046C951CDEB459aF897cff571
f4address (informational only): f410fyk3az77e6ifsarwjkhg6wrm27cl475lrr6myeui
```

I'm not great with JS/ Hardhat, so my troubleshooting has admittedly been limited here. I'd appreciate any ideas on what to try next and am happy to provide any info that might help determine the issue. Thank you!

**Comment by 0xThresh** [comment]
Interestingly, I came back today to try again since I know that Hyperspace just went live. I got a few contracts deployed this time, but eventually ran into the same error as before: 

```
yarn hardhat deploy --reset
yarn run v1.22.19
$ /home/0xthresh/fevm-hardhat-kit/node_modules/.bin/hardhat deploy --reset
You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.

We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
Nothing to compile
Wallet Ethereum Address: 0xc2b60CfFe4f20b2046C951CDEB459aF897cff571
deploying SimpleCoin...
deploying "SimpleCoin" (tx: 0x58fe5aba98a5601639e9a1abd59cbf461ff9f7845a61e0ac8263028e5328347b)...: deployed at 0xD7DF543176f1dfa7CC3596ee835cbd500A9FCD10 with 16123762 gas
deploying MockMinerAPI...
deploying "MockMinerAPI" (tx: 0x0b2e8bab4aba8efeb83816ab2ba05721a644fa816791bd5bd194da38c187eb5f)...: deployed at 0x9aA06654Ac0276AA818924E6bd8c9a83B7e8F6D4 with 29369539 gas
deploying MockMarketAPI...
deploying "MockMarketAPI" (tx: 0x74ce5b0692d7e15f513b7c45743313c5fd314b9f699a28a41c2ffa49fed10da6)...: deployed at 0x2fDf8D4aDd1fFB57077Cd3e7F90c191776255331 with 46503929 gas
Deploying FilecoinMarketConsumer...
deploying "FilecoinMarketConsumer" (tx: 0x5ccffc32ded57179df8de1a1e96f2bb37790dfb893610ed18b0e6b0efa9a43a3)...
/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1814
                for (let i = 0; i < block.transactions.length; i++) {
                                                       ^
TypeError: Cannot read properties of null (reading 'length')
    at Web3Provider.<anonymous> (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1814:56)
    at step (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/home/0xthresh/fevm-hardhat-kit/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by 0xThresh** [comment]
I read in Discord that there was one last Hyperspace upgrade that took place. After trying again today, it appears that everything worked correctly, so I'm going to chalk this one up to being an issue that resulted from the upgrade. 
```
Nothing to compile
Wallet Ethereum Address: 0xc2b60CfFe4f20b2046C951CDEB459aF897cff571
deploying SimpleCoin...
deploying "SimpleCoin" (tx: 0xfc34aca5b3f8101c5394c1edfeaf4cb357af56bae5bc4899e462eadec9cf5ff7)...: deployed at 0x0e72c63aE5aD36d27B1E59bD0fFBd5a0692cD093 with 18373543 gas
deploying MockMinerAPI...
deploying "MockMinerAPI" (tx: 0x96ba75c7c6543104d87d0311a05372690adbada26216ee7e3538617add9e1601)...: deployed at 0xB8BFD317Abbff595D20961AF532cBFFa965338C4 with 31427360 gas
deploying MockMarketAPI...
deploying "MockMarketAPI" (tx: 0x04cebb632602d0fea7a58fa26470348aaeacad34ed1e43be4003e98a051a7e17)...: deployed at 0x28c2e9Bf3A6c41ECB52Ada04123CE81DeaF6Be8b with 47886307 gas
Deploying FilecoinMarketConsumer...
deploying "FilecoinMarketConsumer" (tx: 0xf59c3fd108cc7b06373ba8f7242ab75ea7a1ef33c0e05eb8eff2c874c8ac3ed8)...: deployed at 0x9bAd3331E05D12C27824AE0063822bA57282845A with 52983615 gas
Done in 238.28s.
```
