### ISSUE TITLE
New error running `yarn hardhat deploy`

### ISSUE THREAD

**Issue by emmanuelm41** [filecoin-project/FEVM-Hardhat-Kit#6]
The nonce is different from 0, but I get this nasty error. The address is funded.

```
Nothing to compile
(node:55364) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
nonce: 1
Send faucet funds to this address (f1): f1itpqzzcx6yf52oc35dgsoxfqkoxpy6kdmygbaja
Ethereum deployer address (from f0): 0xff0000000000000000000000000000000000044a
priorityFee:  0x3081d
deploying "SimpleCoin"failed to look up actor state nonce: resolution lookup failed (t410flv6dyymsvufk7dacfq4vqm3a7y6m4ffkeilgn4a): resolve address t410flv6dyymsvufk7dacfq4vqm3a7y6m4ffkeilgn4a: actor not found: validation failure {"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (/Users/emmanuelmurano/Documents/Work/Zondax/otros/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)\n    at LocalAccountsProvider.request (/Users/emmanuelmurano/Documents/Work/Zondax/otros/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":1,"_isProviderError":true} ProviderError: HttpProviderError
    at HttpProvider.request (/Users/emmanuelmurano/Documents/Work/Zondax/otros/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/Users/emmanuelmurano/Documents/Work/Zondax/otros/FEVM-Hardhat-Kit/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
An unexpected error occurred:
```

**Comment by ZakAyesh** [comment]
Thanks for testing Wallaby and Hardhat kit back when they were both in early development. Both the kit and Wallaby have been updated quite a bit and this problem should now be resolved.
